config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :teams
  devise_for :users
  get '/join/team', to: 'teams#join'
  post '/join/team', to: 'teams#join'
  post '/anketa', to: 'forms#submit_form'
  post '/discord', to: 'forms#submit_form_discord'
  post '/discord/send', to: 'discord_notifications#send_notification'
  get '/discord/send', to: 'discord_notifications#new_notification'
  delete '/leave/team/:id', to: 'teams#leave', as: 'leave_team'
  root "home#index", as: :root
  get "/verified_teams", to: "teams#verified_teams", as: :verified_teams
  get "/stream", to: "home#stream", as: :stream

end

app/views/layouts/_aboutsection.html.erb
<p class="countdown main-title-homepage">O DOGODKU</p>
<div class="about-section">
    <div class="about-section-div">
        <p class="about-section-title">Kaj je ERŠ LAN Party?</p>
        <p class="about-section-text">ERŠ LAN Party je dogodek, ki ga organizirajo dijaki Elektro in računalniške šole v Velenju. Dogodek je namenjen vsem, ki jih zanima računalništvo, igranje računalniških iger in druženje z vrstniki. Na dogodku se bodo odvijale različne aktivnosti, kot so igranje računalniških iger, tekmovanja v različnih igrah, VR ipd.</p>
        <p class="about-section-title">Kdaj in kje?</p>
        <p class="about-section-text">ERŠ LAN Party se bo odvijal v prostorih restavracije Gaudeamus v Velenju, in sicer 2. In 3. februarja 2024. Dogodek se bo začel ob 16:00 in končal naslednji dan ob 21:00.</p>
        <p class="about-section-title">Kaj potrebujem?</p>
        <p class="about-section-text">Za udeležbo na dogodku potrebujete računalnik, monitor, tipkovnico, miško in slušalke. Do neke mere jih lahko priskrbi tudi šola, vendar je potrebno to navesti pri prijavi. Priporočamo tudi, da s seboj prinesete kakšen podaljšek in internetni kabel, saj je električnih vtičnic v šoli malo.</p>
    </div>

    <div class="about-section-div">
        <%= image_tag asset_path("gaudic.png"), class:"landing-page"%>
    </div>
</div>

app/views/layouts/_countdown.html.erb
<p class="countdown main-title-homepage">COUNTDOWN</p>

<div class="countdown-div">
  <div class="countown-component">
    <p id="days" class="countdown-text-non-static"></p>
    <p class="countdown-text-static">DNI</p>
  </div>
  <div class="countown-component">
    <p id="hours" class="countdown-text-non-static"></p>
    <p class="countdown-text-static">UR</p>
  </div>
  <div class="countown-component">
    <p id="minutes" class="countdown-text-non-static"></p>
    <p class="countdown-text-static">MIN</p>
  </div>
  <div class="countown-component">
    <p id="seconds" class="countdown-text-non-static"></p>
    <p class="countdown-text-static">SEK</p>
  </div>
</div>


<script>
// Set the date we're counting down to
var countDownDate = new Date("Feb 2, 2024 16:00:00").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();
    
  // Find the distance between now and the count down date
  var distance = countDownDate - now;
    
  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
  // Output the result in an element with id="demo"
  document.getElementById("days").innerHTML = days;
  document.getElementById("hours").innerHTML = hours;
  document.getElementById("minutes").innerHTML = minutes;
  document.getElementById("seconds").innerHTML = seconds;
    
  // If the count down is over, write some text 
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("days").innerHTML = "0";
    document.getElementById("hours").innerHTML = "0";
    document.getElementById("minutes").innerHTML = "0";
    document.getElementById("seconds").innerHTML = "0";
  }
}, 1000);
</script>

app/views/layouts/_discordbanner.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  <strong>Ti QR koda na plakatu ne deluje pravilno?</strong> Poskusi <a href="https://discord.gg/Uavd8mZJjG" target="_blank" class="alert-link">ta link (SPOILER: Discord server je :)</a>.
  <%= button_to '', "/discord?discord_submitted=true", class:'btn-close' %>
</div>

app/views/layouts/_fillform.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Se želiš udeležiti dogodka?</strong> Reši <a href="https://forms.office.com/pages/responsepage.aspx?id=ISkj9tfQGkye7g2hUhMATUMUT-X0C8REvodtX_qv2VpURDZGRjRSQUpEQjlUM1NPR0lMUDBTVjhUQy4u&origin=lprLink" target="_blank" class="alert-link">to anketo</a>  in nam s tem pomagaj pri organizaciji!
  <%= button_to '', "/anketa?anketa_submitted=true", class:'btn-close' %>
</div>

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top fixed-bottom footer">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="text-muted">© 2021 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
     <%= link_to "ERŠ LAN Party", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item <%= 'navbar-active' if current_page?(root_path) %>">
            <%= link_to "Domača stran", root_path, class:"nav-link"%>
        </li>
        <% if ENV['STREAM_ACTIVE'] == 'YES'%>
          <li class="nav-item <%= 'navbar-active' if current_page?(stream_path) %>">
              <%= link_to "Stream", stream_path, class:"nav-link colored-text"%>
          </li>
        <% end %>
        <% if user_signed_in? %>
        <% if current_user && current_user.user_status.name != 'Drugo (Gledalec)' %>
        <li class="nav-item <%= 'navbar-active' if current_page?(teams_path) %>">
            <%= link_to "Moje ekipe", teams_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'navbar-active' if current_page?(new_team_path) %>">
            <%= link_to "Ustvari ekipo", new_team_path, class: "nav-link" %>
        </li>
        
        <% end %>
        
          <% if user_signed_in? && current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Admin plošča", "/admin", class: "nav-link" %>
            </li>
            <li class="nav-item <%= 'navbar-active' if current_page?(discord_send_path) %>">
              <%= link_to "POD", discord_send_path, class: "nav-link" %>
            </li>
          <% end %>
        <% end %>
        <li class="nav-item <%= 'navbar-active' if current_page?(join_team_path) %>">
            <%= link_to "Pridruži se ekipi", "/join/team", class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'navbar-active' if current_page?(verified_teams_path) %>">
            <%= link_to "Potrjene ekipe", verified_teams_path, class: "nav-link" %>
        </li>
      </ul>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="/users/edit">Pozdravljen, <%= current_user.username %></a>
          </li>
          <li class="nav-link login-button-navbar">
            <%= link_to "Odjava", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link login-button-text" %>
        </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_in">Prijava</a>
          </li>
          <li class="nav-item login-button-navbar">
            <a class="nav-link login-button-text" href="/users/sign_up">Registracija</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sponsorsbanner.html.erb
<% image_paths = Dir.glob('app/assets/images/sponsors/*').shuffle.uniq %>
<% total_images = image_paths.length %>
<% min_images_needed = 3 - (total_images % 3) %>


<p class="countdown main-title-homepage">Sponzorji</p>
<div class="custom-carousel">
  <div class="custom-carousel-item">
    <%= link_to "https://eigre.si/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/1.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://komponentko.si/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/12.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  
  <div class="custom-carousel-item">
    <%= link_to "https://www.youtube.com/watch?v=dQw4w9WgXcQ", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/2.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://www.facebook.com/mc.velenje/?locale=sl_SI", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/4.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://store.steampowered.com/app/629760/MORDHAU/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/6.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://kunigunda.si/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/7.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://www.skaza.com/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/8.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://linkomp.si/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/9.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://www.lenovo.com/si/sl/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/10.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://sasainkubator.si/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/11.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://thermoflis.eu/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/13.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
  <div class="custom-carousel-item">
    <%= link_to "https://bazeni.adriapool.si/sl/", target:"_blank" do %>
      <%= image_tag asset_path("sponsors/14.png"), class: 'custom-carousel-image', data: { carousel_target: "slide" } %>
    <% end %>
  </div>
</div>

app/views/layouts/_thanks.html.erb
<p class="countdown main-title-homepage">ZAHVALA</p>
<div class="about-section">
    <div class="about-section-div">
        <p class="about-section-text">Hvala vsem, ki ste se udeležili našega dogodka. Zahvala tudi vsem sponzorjem za nagrade in podporo, brez katerih ne bi bilo mogoče izpeljati tako uspešnega dogodka. Velika zahvala tudi mentorjema in vsem, ki ste s svojim trudom in energijo pomagali pri organizaciji dogodka, vaša predanost je neprecenljiva. Prav tako pa se želim zahvaliti vsem, ki ste s svojim prispevkom omogočili nemoten potek in uspeh tega dogodka. Vaša podpora in angažiranost sta bila ključnega pomena in brez vas to ne bi bilo mogoče. Hvala vam za vaš trud in predanost! Vabimo vas, da se nam pridružite spet drugo leto, saj bomo skupaj ustvarjali nove nepozabne trenutke in doživetja.</p>
    </div>

    <div class="about-section-div">
      <iframe src="https://giphy.com/embed/cJMYXM0g7AqPdbteIP" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen class="landing-page"></iframe><p><a href="https://giphy.com/gifs/thank-you-thx-thanks-again-cJMYXM0g7AqPdbteIP">via GIPHY</a></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ERŠ LAN Party 2023/24</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <%= render 'application/favicon' %>
    <meta name="theme-color" content="#3857F4">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro&display=swap" rel="stylesheet">
  </head>

  <body class="login-back">
    <%= render 'layouts/navbar' %>
    <% if ENV['ANKETA_ACTIVE'] == 'YES' && !cookies[:anketa_banner_closed]%>
      <%= render 'layouts/fillform' %>
    <% end %>
    <% if !cookies[:discord_banner_closed]%>
      <%= render 'layouts/discordbanner' %>
    <% end %> 
    <% flash.each do |key, message| %>
    <div class="toast-container top-0 end-0 p-3">
      <div class="alert <%= flash_class(key) %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>